# Generated by Django 3.2.8 on 2021-11-28 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TA_ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_students', models.BooleanField(blank=True, default=False, null=True)),
                ('can_add_assignments', models.BooleanField(blank=True, default=False, null=True)),
                ('can_add_resources', models.BooleanField(blank=True, default=False, null=True)),
                ('can_notify', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('information', models.CharField(default=1, max_length=1000)),
                ('course_list', models.ManyToManyField(through='TA.TA_ship', to='instructor.Course')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ta_ship',
            name='TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA.teachingassistant'),
        ),
        migrations.AddField(
            model_name='ta_ship',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        ),
        migrations.AlterUniqueTogether(
            name='ta_ship',
            unique_together={('TA', 'course')},
        ),
    ]
